/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLoanSearchRouteImport } from './routes/_authenticated/loan-search'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedIncomeAnalyzerIndexRouteImport } from './routes/_authenticated/income-analyzer.index'
import { Route as AuthenticatedBorrowersIndexRouteImport } from './routes/_authenticated/borrowers.index'
import { Route as AuthenticatedIncomeAnalyzerIdRouteImport } from './routes/_authenticated/income-analyzer.$id'
import { Route as AuthenticatedBorrowersIdRouteImport } from './routes/_authenticated/borrowers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoanSearchRoute = AuthenticatedLoanSearchRouteImport.update({
  id: '/loan-search',
  path: '/loan-search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeAnalyzerIndexRoute =
  AuthenticatedIncomeAnalyzerIndexRouteImport.update({
    id: '/income-analyzer/',
    path: '/income-analyzer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersIndexRoute =
  AuthenticatedBorrowersIndexRouteImport.update({
    id: '/borrowers/',
    path: '/borrowers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomeAnalyzerIdRoute =
  AuthenticatedIncomeAnalyzerIdRouteImport.update({
    id: '/income-analyzer/$id',
    path: '/income-analyzer/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersIdRoute =
  AuthenticatedBorrowersIdRouteImport.update({
    id: '/borrowers/$id',
    path: '/borrowers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/loan-search': typeof AuthenticatedLoanSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/income-analyzer/': typeof AuthenticatedIncomeAnalyzerIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/loan-search': typeof AuthenticatedLoanSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/borrowers': typeof AuthenticatedBorrowersIndexRoute
  '/income-analyzer': typeof AuthenticatedIncomeAnalyzerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/loan-search': typeof AuthenticatedLoanSearchRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/_authenticated/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/_authenticated/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/_authenticated/income-analyzer/': typeof AuthenticatedIncomeAnalyzerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/knowledge'
    | '/loan-search'
    | '/reports'
    | '/settings'
    | '/borrowers/$id'
    | '/income-analyzer/$id'
    | '/borrowers/'
    | '/income-analyzer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/catalog'
    | '/knowledge'
    | '/loan-search'
    | '/reports'
    | '/settings'
    | '/'
    | '/borrowers/$id'
    | '/income-analyzer/$id'
    | '/borrowers'
    | '/income-analyzer'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalog'
    | '/_authenticated/knowledge'
    | '/_authenticated/loan-search'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/borrowers/$id'
    | '/_authenticated/income-analyzer/$id'
    | '/_authenticated/borrowers/'
    | '/_authenticated/income-analyzer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-search': {
      id: '/_authenticated/loan-search'
      path: '/loan-search'
      fullPath: '/loan-search'
      preLoaderRoute: typeof AuthenticatedLoanSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income-analyzer/': {
      id: '/_authenticated/income-analyzer/'
      path: '/income-analyzer'
      fullPath: '/income-analyzer/'
      preLoaderRoute: typeof AuthenticatedIncomeAnalyzerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/': {
      id: '/_authenticated/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof AuthenticatedBorrowersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income-analyzer/$id': {
      id: '/_authenticated/income-analyzer/$id'
      path: '/income-analyzer/$id'
      fullPath: '/income-analyzer/$id'
      preLoaderRoute: typeof AuthenticatedIncomeAnalyzerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/$id': {
      id: '/_authenticated/borrowers/$id'
      path: '/borrowers/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof AuthenticatedBorrowersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLoanSearchRoute: typeof AuthenticatedLoanSearchRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBorrowersIdRoute: typeof AuthenticatedBorrowersIdRoute
  AuthenticatedIncomeAnalyzerIdRoute: typeof AuthenticatedIncomeAnalyzerIdRoute
  AuthenticatedBorrowersIndexRoute: typeof AuthenticatedBorrowersIndexRoute
  AuthenticatedIncomeAnalyzerIndexRoute: typeof AuthenticatedIncomeAnalyzerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLoanSearchRoute: AuthenticatedLoanSearchRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBorrowersIdRoute: AuthenticatedBorrowersIdRoute,
  AuthenticatedIncomeAnalyzerIdRoute: AuthenticatedIncomeAnalyzerIdRoute,
  AuthenticatedBorrowersIndexRoute: AuthenticatedBorrowersIndexRoute,
  AuthenticatedIncomeAnalyzerIndexRoute: AuthenticatedIncomeAnalyzerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
