/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLoanSearchRouteImport } from './routes/_authenticated/loan-search'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedOpsIndexRouteImport } from './routes/_authenticated/ops.index'
import { Route as AuthenticatedIncomeAnalyzerIndexRouteImport } from './routes/_authenticated/income-analyzer.index'
import { Route as AuthenticatedBorrowersIndexRouteImport } from './routes/_authenticated/borrowers.index'
import { Route as AuthenticatedOpsLoansRouteImport } from './routes/_authenticated/ops.loans'
import { Route as AuthenticatedOpsLeadsRouteImport } from './routes/_authenticated/ops.leads'
import { Route as AuthenticatedIncomeAnalyzerIdRouteImport } from './routes/_authenticated/income-analyzer.$id'
import { Route as AuthenticatedBorrowersIdRouteImport } from './routes/_authenticated/borrowers.$id'
import { Route as ApiPublicHooksAutoPayrollRouteImport } from './routes/api/public/hooks/auto-payroll'
import { Route as AuthenticatedOpsLoansIdRouteImport } from './routes/_authenticated/ops.loans.$id'
import { Route as AuthenticatedOpsLeadsIdRouteImport } from './routes/_authenticated/ops.leads.$id'
import { Route as AuthenticatedOpsAdminWebhooksRouteImport } from './routes/_authenticated/ops.admin.webhooks'
import { Route as AuthenticatedOpsAdminUsersRouteImport } from './routes/_authenticated/ops.admin.users'
import { Route as AuthenticatedOpsAdminProductionRouteImport } from './routes/_authenticated/ops.admin.production'
import { Route as AuthenticatedOpsAdminPayrollRouteImport } from './routes/_authenticated/ops.admin.payroll'
import { Route as AuthenticatedOpsAdminLeadSourcesRouteImport } from './routes/_authenticated/ops.admin.lead-sources'
import { Route as AuthenticatedOpsAdminExpensesRouteImport } from './routes/_authenticated/ops.admin.expenses'
import { Route as ApiPublicWebhooksLeadsSourceRouteImport } from './routes/api/public/webhooks/leads.$source'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoanSearchRoute = AuthenticatedLoanSearchRouteImport.update({
  id: '/loan-search',
  path: '/loan-search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpsIndexRoute = AuthenticatedOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeAnalyzerIndexRoute =
  AuthenticatedIncomeAnalyzerIndexRouteImport.update({
    id: '/income-analyzer/',
    path: '/income-analyzer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersIndexRoute =
  AuthenticatedBorrowersIndexRouteImport.update({
    id: '/borrowers/',
    path: '/borrowers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsLoansRoute = AuthenticatedOpsLoansRouteImport.update({
  id: '/ops/loans',
  path: '/ops/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpsLeadsRoute = AuthenticatedOpsLeadsRouteImport.update({
  id: '/ops/leads',
  path: '/ops/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeAnalyzerIdRoute =
  AuthenticatedIncomeAnalyzerIdRouteImport.update({
    id: '/income-analyzer/$id',
    path: '/income-analyzer/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersIdRoute =
  AuthenticatedBorrowersIdRouteImport.update({
    id: '/borrowers/$id',
    path: '/borrowers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksAutoPayrollRoute =
  ApiPublicHooksAutoPayrollRouteImport.update({
    id: '/api/public/hooks/auto-payroll',
    path: '/api/public/hooks/auto-payroll',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOpsLoansIdRoute = AuthenticatedOpsLoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOpsLoansRoute,
} as any)
const AuthenticatedOpsLeadsIdRoute = AuthenticatedOpsLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOpsLeadsRoute,
} as any)
const AuthenticatedOpsAdminWebhooksRoute =
  AuthenticatedOpsAdminWebhooksRouteImport.update({
    id: '/ops/admin/webhooks',
    path: '/ops/admin/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsAdminUsersRoute =
  AuthenticatedOpsAdminUsersRouteImport.update({
    id: '/ops/admin/users',
    path: '/ops/admin/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsAdminProductionRoute =
  AuthenticatedOpsAdminProductionRouteImport.update({
    id: '/ops/admin/production',
    path: '/ops/admin/production',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsAdminPayrollRoute =
  AuthenticatedOpsAdminPayrollRouteImport.update({
    id: '/ops/admin/payroll',
    path: '/ops/admin/payroll',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsAdminLeadSourcesRoute =
  AuthenticatedOpsAdminLeadSourcesRouteImport.update({
    id: '/ops/admin/lead-sources',
    path: '/ops/admin/lead-sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsAdminExpensesRoute =
  AuthenticatedOpsAdminExpensesRouteImport.update({
    id: '/ops/admin/expenses',
    path: '/ops/admin/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhooksLeadsSourceRoute =
  ApiPublicWebhooksLeadsSourceRouteImport.update({
    id: '/api/public/webhooks/leads/$source',
    path: '/api/public/webhooks/leads/$source',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/loan-search': typeof AuthenticatedLoanSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/ops/leads': typeof AuthenticatedOpsLeadsRouteWithChildren
  '/ops/loans': typeof AuthenticatedOpsLoansRouteWithChildren
  '/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/income-analyzer/': typeof AuthenticatedIncomeAnalyzerIndexRoute
  '/ops/': typeof AuthenticatedOpsIndexRoute
  '/ops/admin/expenses': typeof AuthenticatedOpsAdminExpensesRoute
  '/ops/admin/lead-sources': typeof AuthenticatedOpsAdminLeadSourcesRoute
  '/ops/admin/payroll': typeof AuthenticatedOpsAdminPayrollRoute
  '/ops/admin/production': typeof AuthenticatedOpsAdminProductionRoute
  '/ops/admin/users': typeof AuthenticatedOpsAdminUsersRoute
  '/ops/admin/webhooks': typeof AuthenticatedOpsAdminWebhooksRoute
  '/ops/leads/$id': typeof AuthenticatedOpsLeadsIdRoute
  '/ops/loans/$id': typeof AuthenticatedOpsLoansIdRoute
  '/api/public/hooks/auto-payroll': typeof ApiPublicHooksAutoPayrollRoute
  '/api/public/webhooks/leads/$source': typeof ApiPublicWebhooksLeadsSourceRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/loan-search': typeof AuthenticatedLoanSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/ops/leads': typeof AuthenticatedOpsLeadsRouteWithChildren
  '/ops/loans': typeof AuthenticatedOpsLoansRouteWithChildren
  '/borrowers': typeof AuthenticatedBorrowersIndexRoute
  '/income-analyzer': typeof AuthenticatedIncomeAnalyzerIndexRoute
  '/ops': typeof AuthenticatedOpsIndexRoute
  '/ops/admin/expenses': typeof AuthenticatedOpsAdminExpensesRoute
  '/ops/admin/lead-sources': typeof AuthenticatedOpsAdminLeadSourcesRoute
  '/ops/admin/payroll': typeof AuthenticatedOpsAdminPayrollRoute
  '/ops/admin/production': typeof AuthenticatedOpsAdminProductionRoute
  '/ops/admin/users': typeof AuthenticatedOpsAdminUsersRoute
  '/ops/admin/webhooks': typeof AuthenticatedOpsAdminWebhooksRoute
  '/ops/leads/$id': typeof AuthenticatedOpsLeadsIdRoute
  '/ops/loans/$id': typeof AuthenticatedOpsLoansIdRoute
  '/api/public/hooks/auto-payroll': typeof ApiPublicHooksAutoPayrollRoute
  '/api/public/webhooks/leads/$source': typeof ApiPublicWebhooksLeadsSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/loan-search': typeof AuthenticatedLoanSearchRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/borrowers/$id': typeof AuthenticatedBorrowersIdRoute
  '/_authenticated/income-analyzer/$id': typeof AuthenticatedIncomeAnalyzerIdRoute
  '/_authenticated/ops/leads': typeof AuthenticatedOpsLeadsRouteWithChildren
  '/_authenticated/ops/loans': typeof AuthenticatedOpsLoansRouteWithChildren
  '/_authenticated/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/_authenticated/income-analyzer/': typeof AuthenticatedIncomeAnalyzerIndexRoute
  '/_authenticated/ops/': typeof AuthenticatedOpsIndexRoute
  '/_authenticated/ops/admin/expenses': typeof AuthenticatedOpsAdminExpensesRoute
  '/_authenticated/ops/admin/lead-sources': typeof AuthenticatedOpsAdminLeadSourcesRoute
  '/_authenticated/ops/admin/payroll': typeof AuthenticatedOpsAdminPayrollRoute
  '/_authenticated/ops/admin/production': typeof AuthenticatedOpsAdminProductionRoute
  '/_authenticated/ops/admin/users': typeof AuthenticatedOpsAdminUsersRoute
  '/_authenticated/ops/admin/webhooks': typeof AuthenticatedOpsAdminWebhooksRoute
  '/_authenticated/ops/leads/$id': typeof AuthenticatedOpsLeadsIdRoute
  '/_authenticated/ops/loans/$id': typeof AuthenticatedOpsLoansIdRoute
  '/api/public/hooks/auto-payroll': typeof ApiPublicHooksAutoPayrollRoute
  '/api/public/webhooks/leads/$source': typeof ApiPublicWebhooksLeadsSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/knowledge'
    | '/loan-search'
    | '/reports'
    | '/settings'
    | '/borrowers/$id'
    | '/income-analyzer/$id'
    | '/ops/leads'
    | '/ops/loans'
    | '/borrowers/'
    | '/income-analyzer/'
    | '/ops/'
    | '/ops/admin/expenses'
    | '/ops/admin/lead-sources'
    | '/ops/admin/payroll'
    | '/ops/admin/production'
    | '/ops/admin/users'
    | '/ops/admin/webhooks'
    | '/ops/leads/$id'
    | '/ops/loans/$id'
    | '/api/public/hooks/auto-payroll'
    | '/api/public/webhooks/leads/$source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/catalog'
    | '/knowledge'
    | '/loan-search'
    | '/reports'
    | '/settings'
    | '/'
    | '/borrowers/$id'
    | '/income-analyzer/$id'
    | '/ops/leads'
    | '/ops/loans'
    | '/borrowers'
    | '/income-analyzer'
    | '/ops'
    | '/ops/admin/expenses'
    | '/ops/admin/lead-sources'
    | '/ops/admin/payroll'
    | '/ops/admin/production'
    | '/ops/admin/users'
    | '/ops/admin/webhooks'
    | '/ops/leads/$id'
    | '/ops/loans/$id'
    | '/api/public/hooks/auto-payroll'
    | '/api/public/webhooks/leads/$source'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalog'
    | '/_authenticated/knowledge'
    | '/_authenticated/loan-search'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/borrowers/$id'
    | '/_authenticated/income-analyzer/$id'
    | '/_authenticated/ops/leads'
    | '/_authenticated/ops/loans'
    | '/_authenticated/borrowers/'
    | '/_authenticated/income-analyzer/'
    | '/_authenticated/ops/'
    | '/_authenticated/ops/admin/expenses'
    | '/_authenticated/ops/admin/lead-sources'
    | '/_authenticated/ops/admin/payroll'
    | '/_authenticated/ops/admin/production'
    | '/_authenticated/ops/admin/users'
    | '/_authenticated/ops/admin/webhooks'
    | '/_authenticated/ops/leads/$id'
    | '/_authenticated/ops/loans/$id'
    | '/api/public/hooks/auto-payroll'
    | '/api/public/webhooks/leads/$source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAutoPayrollRoute: typeof ApiPublicHooksAutoPayrollRoute
  ApiPublicWebhooksLeadsSourceRoute: typeof ApiPublicWebhooksLeadsSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-search': {
      id: '/_authenticated/loan-search'
      path: '/loan-search'
      fullPath: '/loan-search'
      preLoaderRoute: typeof AuthenticatedLoanSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/': {
      id: '/_authenticated/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof AuthenticatedOpsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income-analyzer/': {
      id: '/_authenticated/income-analyzer/'
      path: '/income-analyzer'
      fullPath: '/income-analyzer/'
      preLoaderRoute: typeof AuthenticatedIncomeAnalyzerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/': {
      id: '/_authenticated/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof AuthenticatedBorrowersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/loans': {
      id: '/_authenticated/ops/loans'
      path: '/ops/loans'
      fullPath: '/ops/loans'
      preLoaderRoute: typeof AuthenticatedOpsLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/leads': {
      id: '/_authenticated/ops/leads'
      path: '/ops/leads'
      fullPath: '/ops/leads'
      preLoaderRoute: typeof AuthenticatedOpsLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income-analyzer/$id': {
      id: '/_authenticated/income-analyzer/$id'
      path: '/income-analyzer/$id'
      fullPath: '/income-analyzer/$id'
      preLoaderRoute: typeof AuthenticatedIncomeAnalyzerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/$id': {
      id: '/_authenticated/borrowers/$id'
      path: '/borrowers/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof AuthenticatedBorrowersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/auto-payroll': {
      id: '/api/public/hooks/auto-payroll'
      path: '/api/public/hooks/auto-payroll'
      fullPath: '/api/public/hooks/auto-payroll'
      preLoaderRoute: typeof ApiPublicHooksAutoPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ops/loans/$id': {
      id: '/_authenticated/ops/loans/$id'
      path: '/$id'
      fullPath: '/ops/loans/$id'
      preLoaderRoute: typeof AuthenticatedOpsLoansIdRouteImport
      parentRoute: typeof AuthenticatedOpsLoansRoute
    }
    '/_authenticated/ops/leads/$id': {
      id: '/_authenticated/ops/leads/$id'
      path: '/$id'
      fullPath: '/ops/leads/$id'
      preLoaderRoute: typeof AuthenticatedOpsLeadsIdRouteImport
      parentRoute: typeof AuthenticatedOpsLeadsRoute
    }
    '/_authenticated/ops/admin/webhooks': {
      id: '/_authenticated/ops/admin/webhooks'
      path: '/ops/admin/webhooks'
      fullPath: '/ops/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedOpsAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/admin/users': {
      id: '/_authenticated/ops/admin/users'
      path: '/ops/admin/users'
      fullPath: '/ops/admin/users'
      preLoaderRoute: typeof AuthenticatedOpsAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/admin/production': {
      id: '/_authenticated/ops/admin/production'
      path: '/ops/admin/production'
      fullPath: '/ops/admin/production'
      preLoaderRoute: typeof AuthenticatedOpsAdminProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/admin/payroll': {
      id: '/_authenticated/ops/admin/payroll'
      path: '/ops/admin/payroll'
      fullPath: '/ops/admin/payroll'
      preLoaderRoute: typeof AuthenticatedOpsAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/admin/lead-sources': {
      id: '/_authenticated/ops/admin/lead-sources'
      path: '/ops/admin/lead-sources'
      fullPath: '/ops/admin/lead-sources'
      preLoaderRoute: typeof AuthenticatedOpsAdminLeadSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/admin/expenses': {
      id: '/_authenticated/ops/admin/expenses'
      path: '/ops/admin/expenses'
      fullPath: '/ops/admin/expenses'
      preLoaderRoute: typeof AuthenticatedOpsAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/leads/$source': {
      id: '/api/public/webhooks/leads/$source'
      path: '/api/public/webhooks/leads/$source'
      fullPath: '/api/public/webhooks/leads/$source'
      preLoaderRoute: typeof ApiPublicWebhooksLeadsSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOpsLeadsRouteChildren {
  AuthenticatedOpsLeadsIdRoute: typeof AuthenticatedOpsLeadsIdRoute
}

const AuthenticatedOpsLeadsRouteChildren: AuthenticatedOpsLeadsRouteChildren = {
  AuthenticatedOpsLeadsIdRoute: AuthenticatedOpsLeadsIdRoute,
}

const AuthenticatedOpsLeadsRouteWithChildren =
  AuthenticatedOpsLeadsRoute._addFileChildren(
    AuthenticatedOpsLeadsRouteChildren,
  )

interface AuthenticatedOpsLoansRouteChildren {
  AuthenticatedOpsLoansIdRoute: typeof AuthenticatedOpsLoansIdRoute
}

const AuthenticatedOpsLoansRouteChildren: AuthenticatedOpsLoansRouteChildren = {
  AuthenticatedOpsLoansIdRoute: AuthenticatedOpsLoansIdRoute,
}

const AuthenticatedOpsLoansRouteWithChildren =
  AuthenticatedOpsLoansRoute._addFileChildren(
    AuthenticatedOpsLoansRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLoanSearchRoute: typeof AuthenticatedLoanSearchRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBorrowersIdRoute: typeof AuthenticatedBorrowersIdRoute
  AuthenticatedIncomeAnalyzerIdRoute: typeof AuthenticatedIncomeAnalyzerIdRoute
  AuthenticatedOpsLeadsRoute: typeof AuthenticatedOpsLeadsRouteWithChildren
  AuthenticatedOpsLoansRoute: typeof AuthenticatedOpsLoansRouteWithChildren
  AuthenticatedBorrowersIndexRoute: typeof AuthenticatedBorrowersIndexRoute
  AuthenticatedIncomeAnalyzerIndexRoute: typeof AuthenticatedIncomeAnalyzerIndexRoute
  AuthenticatedOpsIndexRoute: typeof AuthenticatedOpsIndexRoute
  AuthenticatedOpsAdminExpensesRoute: typeof AuthenticatedOpsAdminExpensesRoute
  AuthenticatedOpsAdminLeadSourcesRoute: typeof AuthenticatedOpsAdminLeadSourcesRoute
  AuthenticatedOpsAdminPayrollRoute: typeof AuthenticatedOpsAdminPayrollRoute
  AuthenticatedOpsAdminProductionRoute: typeof AuthenticatedOpsAdminProductionRoute
  AuthenticatedOpsAdminUsersRoute: typeof AuthenticatedOpsAdminUsersRoute
  AuthenticatedOpsAdminWebhooksRoute: typeof AuthenticatedOpsAdminWebhooksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLoanSearchRoute: AuthenticatedLoanSearchRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBorrowersIdRoute: AuthenticatedBorrowersIdRoute,
  AuthenticatedIncomeAnalyzerIdRoute: AuthenticatedIncomeAnalyzerIdRoute,
  AuthenticatedOpsLeadsRoute: AuthenticatedOpsLeadsRouteWithChildren,
  AuthenticatedOpsLoansRoute: AuthenticatedOpsLoansRouteWithChildren,
  AuthenticatedBorrowersIndexRoute: AuthenticatedBorrowersIndexRoute,
  AuthenticatedIncomeAnalyzerIndexRoute: AuthenticatedIncomeAnalyzerIndexRoute,
  AuthenticatedOpsIndexRoute: AuthenticatedOpsIndexRoute,
  AuthenticatedOpsAdminExpensesRoute: AuthenticatedOpsAdminExpensesRoute,
  AuthenticatedOpsAdminLeadSourcesRoute: AuthenticatedOpsAdminLeadSourcesRoute,
  AuthenticatedOpsAdminPayrollRoute: AuthenticatedOpsAdminPayrollRoute,
  AuthenticatedOpsAdminProductionRoute: AuthenticatedOpsAdminProductionRoute,
  AuthenticatedOpsAdminUsersRoute: AuthenticatedOpsAdminUsersRoute,
  AuthenticatedOpsAdminWebhooksRoute: AuthenticatedOpsAdminWebhooksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAutoPayrollRoute: ApiPublicHooksAutoPayrollRoute,
  ApiPublicWebhooksLeadsSourceRoute: ApiPublicWebhooksLeadsSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
