-- Bulk import: 15 lenders, 121 programs from MPS Wholesale Lender Matrix
DELETE FROM public.loan_programs;
DELETE FROM public.lenders;

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Brokers First Funding', 'Strong NonQM + full govt suite. 90% LTV NonQM. FN DSCR investment. NHF DPA.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (
  lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months,
  occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount,
  bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible,
  dpa_available, gift_funds_allowed, special_programs, notes, tags
)
SELECT ins_lender.id, x.product_name, x.loan_program, x.product_type, x.min_fico, x.max_ltv, x.max_dti, x.reserve_months,
       x.occupancies, x.property_types, x.income_types, x.loan_types, x.states, x.min_loan_amount, x.max_loan_amount,
       x.bk_seasoning_months, x.fc_seasoning_months, x.dscr_min, x.foreign_national_eligible, x.itin_eligible,
       x.dpa_available, x.gift_funds_allowed, x.special_programs, x.notes, x.tags
FROM ins_lender, (VALUES
('Bank Stmt / Expanded Doc'::text,'Bank Stmt / Expanded Doc'::text,'Non-QM'::text,640,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Expanded','Full Doc'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL::numeric,false,false,false,true,ARRAY[]::text[],'12/24mo Bank Stmt or Full Doc. Max 90% purchase at 720+ FICO ≤$1.5M. 48mo BK/FC/SS/DIL.','{Bank Statement,Expanded,Full Doc}'::text[]),
('Full Doc Non-QM','Full Doc Non-QM','Non-QM',640,90.0,55.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'W2/Tax Returns. Same LTV grid as expanded. 55% DTI primary w/ restrictions.','{"Full Doc"}'),
('DSCR 1-4 Unit','DSCR 1-4 Unit','Non-QM',640,85.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3500000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.00 and <1.00 matrices. LTV>80% req: 740 FICO, 1 unit, experienced investor, DSCR≥1.25.','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',700,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],400000.0,2000000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'700+ FICO. No first-time investors/homebuyers. Experienced only.','{DSCR}'),
('Foreign National Investment','Foreign National Investment','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],100000.0,1500000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'DSCR ≥1.00. 680+ or foreign credit. OFAC required. Impounds required.','{"Foreign National",DSCR}'),
('ITIN Full/Expanded','ITIN Full/Expanded','Non-QM',700,80.0,50.0,3,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Expanded'],ARRAY['ITIN','Full Doc','Expanded'],ARRAY['ALL'],150000.0,1500000.0,48,48,NULL,false,true,false,true,ARRAY[]::text[],'ITIN holders — primary and 2nd home only. 700+ FICO: 80% purchase up to $1.5M.','{ITIN,"Full Doc",Expanded}'),
('FHA','FHA','Agency',580,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Min 580 FICO AUS. Manufactured homes eligible. Non-perm residents post 5/25/2025 ineligible.','{FHA}'),
('VA','VA','Agency',580,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['VA'],ARRAY['VA'],ARRAY['ALL'],100000.0,1500000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'580 FICO purchase 100% ≤$1M. >$1M-$1.5M req 680. C/O 100% ≤$1M.','{VA}'),
('Freddie Mac Standard / Super Conforming','Freddie Mac Standard / Super Conforming','Agency',620,95.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'DU/LPA. Primary SFR 95% P&RT 80% C/O. HomeOne 97% FTHB. DACA ineligible.','{Conventional,"Full Doc"}'),
('NHF DPA (Repayable & Forgivable)','NHF DPA','Agency',600,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA','VA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,true,true,ARRAY[]::text[],'3.5% or 5% DPA. FHA only. Min 600 AUS / 660 manual. Repayable note rate +2% 10yr.','{FHA,VA}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Click n'' Close', 'SmartBuy DPA — 3yr/5yr forgivable or 10yr repayable. 203(k) standard and limited.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('SmartBuy DPA'::text,'SmartBuy DPA'::text,'Agency'::text,640,96.5,NULL::numeric,NULL::int,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA','USDA'],ARRAY['FHA','USDA'],ARRAY['ALL'],100000.0,NULL::numeric,NULL::int,NULL::int,NULL::numeric,false,false,true,true,ARRAY[]::text[],'3.5% or 5% DPA. 3yr/5yr forgivable, 10yr repayable, closing cost repayable. No FTHB req.','{FHA,USDA}'::text[]),
('FHA 203(k) Standard','FHA 203(k) Standard','Agency',640,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc','FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Min $5K repairs. HUD consultant required. 1-4 unit primary. 6mo completion.','{"Full Doc",FHA}'),
('FHA 203(k) Limited','FHA 203(k) Limited','Agency',640,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc','FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Max $35K repairs. No HUD consultant. Cosmetic/non-structural only.','{"Full Doc",FHA}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Equity Prime Mortgage', 'Wide government + NonQM stack. EPM Elite up to 90% LTV. VA manual UW allowed. Choice Renovation.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('FHA Standard'::text,'FHA Standard'::text,'Agency'::text,580,96.5,NULL::numeric,NULL::int,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL::numeric,NULL::int,NULL::int,NULL::numeric,false,false,false,true,ARRAY[]::text[],'Standard FHA AUS. Manual UW allowed.','{FHA}'::text[]),
('FHA 203(k) Standard & Limited','FHA 203(k) Standard & Limited','Agency',580,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard ($5K+, consultant) and Limited ($35K max).','{FHA}'),
('FHA 203(h) Disaster Relief','FHA 203(h) Disaster Relief','Agency',580,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'100% LTV for disaster-affected. Case # within 1yr of PDMDA.','{FHA}'),
('VA','VA','Agency',500,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['VA'],ARRAY['VA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Manual UW allowed. 500 FICO floor.','{VA}'),
('USDA','USDA','Agency',620,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR'],ARRAY['Full Doc'],ARRAY['USDA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Rural areas. GUS approval required.','{USDA}'),
('Conventional Conforming','Conventional Conforming','Agency',620,97.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'HomeReady/Home Possible 97% FTHB.','{Conventional,"Full Doc"}'),
('EPM Prime Non-QM','EPM Prime Non-QM','Non-QM',620,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc','Asset Utilization'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],150000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt, P&L, asset depletion. To 90%.','{"Bank Statement","Full Doc"}'),
('EPM Elite Non-QM','EPM Elite Non-QM','Non-QM',680,90.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['ALL'],150000.0,3000000.0,24,24,NULL,false,false,false,true,ARRAY[]::text[],'Premium tier. To 90% LTV. Stronger pricing.','{"Bank Statement","Full Doc","P&L"}'),
('Aspire DSCR 1-4','Aspire DSCR 1-4','Non-QM',640,85.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0. STR allowed.','{DSCR}'),
('Aspire DSCR 5-8','Aspire DSCR 5-8','Non-QM',700,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],400000.0,2500000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit residential. Experienced investor.','{DSCR}'),
('ITIN Core','ITIN Core','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['ITIN','Full Doc'],ARRAY['ALL'],100000.0,1500000.0,48,48,NULL,false,true,false,true,ARRAY[]::text[],'ITIN borrowers. Primary/2nd home.','{ITIN,"Full Doc"}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',NULL,65.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],150000.0,2000000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'No FICO required. 65% LTV cap. OFAC.','{"Foreign National",DSCR}'),
('Choice Renovation','Choice Renovation','Agency',620,97.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Conventional renovation. Repairs financed in loan.','{Conventional,"Full Doc"}'),
('Jumbo','Jumbo','Agency',700,89.99,43.0,6,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],766550.0,3000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'AUS jumbo. 89.99% to $1.5M with MI.','{Jumbo,"Full Doc"}'),
('Conventional Investor','Conventional Investor','Agency',640,85.0,NULL,NULL,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Investment property conforming.','{Conventional,"Full Doc"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);