WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Lead+ Wholesale', 'Closed-End Seconds standalone product. ITIN Plus up to 85% LTV. DSCR <1.00 allowed.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Alt Doc Non-QM'::text,'Alt Doc Non-QM'::text,'Non-QM'::text,620,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','P&L','1099','WVOE'],ARRAY['Bank Statement','P&L','1099'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL::numeric,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt, P&L, 1099, WVOE.','{"Bank Statement","P&L","1099"}'::text[]),
('Full Doc Non-QM','Full Doc Non-QM','Non-QM',620,90.0,55.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'W2/Tax Returns full doc.','{"Full Doc"}'),
('DSCR 1-4 Unit','DSCR 1-4 Unit','Non-QM',620,85.0,NULL,3,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3500000.0,48,48,0.75,false,false,false,true,ARRAY[]::text[],'DSCR <1.00 allowed at lower LTV.','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],250000.0,3000000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit DSCR.','{DSCR}'),
('ITIN Plus','ITIN Plus','Non-QM',680,85.0,50.0,3,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['ITIN','Full Doc','Bank Statement'],ARRAY['ALL'],100000.0,1500000.0,48,48,NULL,false,true,false,true,ARRAY[]::text[],'ITIN to 85% LTV — best in class.','{ITIN,"Full Doc","Bank Statement"}'),
('Life Force Closed-End Second','Closed-End Second (CES)','Non-QM',720,90.0,50.0,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement','DSCR'],ARRAY['Full Doc','Bank Statement','DSCR'],ARRAY['ALL'],50000.0,350000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standalone 2nd lien. 90% CLTV. No piggyback.','{"Full Doc","Bank Statement",DSCR}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('LoanStream Mortgage', 'DSCR Fusion unique product. Sub1 and No Ratio DSCR tiers. Closed-End Seconds.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('NonQM Core'::text,'NonQM Core'::text,'Non-QM'::text,700,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL::numeric,false,false,false,true,ARRAY[]::text[],'Bank stmt, full doc, P&L. To 90% LTV.','{"Bank Statement","Full Doc","P&L"}'::text[]),
('NonQM Select','NonQM Select','Non-QM',680,85.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],100000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Wider credit box at lower LTV.','{"Bank Statement","Full Doc"}'),
('DSCR 1-4 Unit','DSCR 1-4 Unit','Non-QM',680,85.0,NULL,3,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'Standard DSCR ≥1.0.','{DSCR}'),
('DSCR Sub1','DSCR Sub1','Non-QM',700,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2000000.0,48,48,0.75,false,false,false,true,ARRAY[]::text[],'DSCR 0.75-0.99 allowed.','{DSCR}'),
('DSCR No Ratio','DSCR No Ratio','Non-QM',720,70.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,1500000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'No DSCR threshold. Property only.','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',700,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],250000.0,2500000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit DSCR.','{DSCR}'),
('DSCR Fusion','DSCR Fusion','Non-QM',700,80.0,50.0,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR','Full Doc'],ARRAY['DSCR','Full Doc'],ARRAY['ALL'],150000.0,2000000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'Hybrid DSCR + personal income qualifier.','{DSCR,"Full Doc"}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',680,70.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],150000.0,1500000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'FN investment DSCR.','{"Foreign National",DSCR}'),
('Closed-End Second','Closed-End Second','Non-QM',700,90.0,50.0,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['Full Doc','Bank Statement'],ARRAY['ALL'],50000.0,350000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Concurrent piggyback allowed.','{"Full Doc","Bank Statement"}'),
('Conventional Conforming','Conventional Conforming','Agency',620,97.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard conforming.','{Conventional,"Full Doc"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Pennymac TPO', 'Perfect Rate™ & Perfect Term™ tools. OptiMIze™ MI. Top 3 wholesale lender scale.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('FHA'::text,'FHA'::text,'Agency'::text,580,96.5,NULL::numeric,NULL::int,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL::numeric,NULL::int,NULL::int,NULL::numeric,false,false,false,true,ARRAY[]::text[],'Standard FHA. 580 FICO.','{FHA}'::text[]),
('VA','VA','Agency',620,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['VA'],ARRAY['VA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard VA AUS.','{VA}'),
('USDA','USDA','Agency',640,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR'],ARRAY['Full Doc'],ARRAY['USDA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'GUS approval.','{USDA}'),
('Conventional Conforming','Conventional Conforming','Agency',620,97.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'HomeReady 97%.','{Conventional,"Full Doc"}'),
('AUS Jumbo','AUS Jumbo','Agency',700,89.99,43.0,6,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],766550.0,3500000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'AUS-driven jumbo. 89.99% LTV w/ MI.','{Jumbo,"Full Doc"}'),
('Non-QM','Non-QM','Non-QM',660,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],150000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Bank stmt + full doc Non-QM.','{"Bank Statement","Full Doc"}'),
('DSCR','DSCR','Non-QM',680,80.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2500000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0.','{DSCR}'),
('HELOC 2nd','HELOC 2nd','Non-QM',680,85.0,50.0,NULL,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],25000.0,500000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Stand-alone HELOC 2nd lien.','{"Full Doc"}'),
('Closed-End Second','Closed-End Second','Non-QM',680,85.0,50.0,NULL,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],25000.0,500000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'CES fixed 2nd.','{"Full Doc"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Champions Funding', 'Super Jumbo to $5M. No Ratio DSCR. FN DSCR. Accelerator/Activator program suite.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Accelerator Full Doc'::text,'Accelerator Full Doc'::text,'Non-QM'::text,600,90.0,55.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,4000000.0,36,36,NULL::numeric,false,false,false,true,ARRAY[]::text[],'Full doc Non-QM. To 90% LTV.','{"Full Doc"}'::text[]),
('Accelerator Bank Statement','Accelerator Bank Statement','Non-QM',620,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['Bank Statement'],ARRAY['ALL'],150000.0,4000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt.','{"Bank Statement"}'),
('Activator P&L','Activator P&L','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['P&L'],ARRAY['P&L'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'CPA-prepared P&L.','{"P&L"}'),
('Activator 1099','Activator 1099','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['1099'],ARRAY['1099'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'1099 contractor income.','{"1099"}'),
('Activator Asset Utilization','Activator Asset Utilization','Non-QM',680,80.0,NULL,12,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Asset Utilization'],ARRAY['Asset Utilization'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'Asset depletion qualifier.','{"Asset Utilization"}'),
('DSCR Standard','DSCR Standard','Non-QM',640,85.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0.','{DSCR}'),
('DSCR No Ratio','DSCR No Ratio','Non-QM',680,80.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'Qualify on property — zero DSCR threshold.','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],250000.0,2500000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit DSCR.','{DSCR}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',NULL,75.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],150000.0,2000000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'No FICO required. OFAC.','{"Foreign National",DSCR}'),
('ITIN','ITIN','Non-QM',640,80.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['ITIN','Full Doc','Bank Statement'],ARRAY['ALL'],100000.0,1500000.0,36,36,NULL,false,true,false,true,ARRAY[]::text[],'ITIN borrowers.','{ITIN,"Full Doc","Bank Statement"}'),
('Super Jumbo','Super Jumbo','Non-QM',720,80.0,43.0,12,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['Jumbo','Full Doc','Bank Statement'],ARRAY['ALL'],2000000.0,5000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'To $5M Super Jumbo.','{Jumbo,"Full Doc","Bank Statement"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Lima One Capital', 'Hard money/bridge only. Not a traditional mortgage lender. Investor construction focus.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Fix & Flip'::text,'Fix & Flip'::text,'Non-QM'::text,660,95.0,NULL::numeric,3,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],75000.0,3000000.0,NULL::int,NULL::int,NULL::numeric,false,false,false,true,ARRAY[]::text[],'95% LTC. Hard money. 12-24mo terms. Draw-based.','{"Full Doc"}'::text[]),
('Bridge','Bridge','Non-QM',660,80.0,NULL,3,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],75000.0,3000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Bridge financing. 12mo terms.','{"Full Doc"}'),
('New Construction','New Construction','Non-QM',680,90.0,NULL,6,ARRAY['Investment'],ARRAY['SFR'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],100000.0,5000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Ground-up construction for investors.','{"Full Doc"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('A&D Mortgage', 'AD Power Jumbo to $5M. DSCR as low as 0. Aggressive bank statement to 90%. 12mo from BK/FC.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Bank Statement'::text,'Bank Statement'::text,'Non-QM'::text,620,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['Bank Statement'],ARRAY['ALL'],100000.0,4000000.0,12,12,NULL::numeric,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt to 90%. 12mo from BK/FC.','{"Bank Statement"}'::text[]),
('P&L Only','P&L Only','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['P&L'],ARRAY['P&L'],ARRAY['ALL'],100000.0,3000000.0,12,12,NULL,false,false,false,true,ARRAY[]::text[],'CPA-prepared P&L only.','{"P&L"}'),
('WVOE','WVOE','Non-QM',680,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],100000.0,2000000.0,24,24,NULL,false,false,false,true,ARRAY[]::text[],'Written verification of employment only.','{"Full Doc"}'),
('1099','1099','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['1099'],ARRAY['1099'],ARRAY['ALL'],100000.0,3000000.0,12,12,NULL,false,false,false,true,ARRAY[]::text[],'1099 contractor income.','{"1099"}'),
('DSCR','DSCR','Non-QM',620,85.0,NULL,3,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3500000.0,12,12,0.0,false,false,false,true,ARRAY[]::text[],'DSCR as low as 0 (No Ratio).','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],200000.0,3000000.0,12,12,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit DSCR.','{DSCR}'),
('ITIN','ITIN','Non-QM',640,85.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['ITIN','Full Doc','Bank Statement'],ARRAY['ALL'],100000.0,1500000.0,12,12,NULL,false,true,false,true,ARRAY[]::text[],'ITIN borrowers.','{ITIN,"Full Doc","Bank Statement"}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',680,75.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],150000.0,2000000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'FN DSCR investment.','{"Foreign National",DSCR}'),
('Conventional','Conventional','Agency',620,97.0,NULL,NULL,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard conforming.','{Conventional,"Full Doc"}'),
('AD Power Jumbo','AD Power Jumbo','Non-QM',700,85.0,43.0,12,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Bank Statement'],ARRAY['Jumbo','Full Doc','Bank Statement'],ARRAY['ALL'],1000000.0,5000000.0,24,24,NULL,false,false,false,true,ARRAY[]::text[],'To $5M Power Jumbo.','{Jumbo,"Full Doc","Bank Statement"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);