WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Change Wholesale', 'Only lender with certified CDFI / ATR-exempt product. DACA eligible (Express). Community Mortgage unique.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Community Mortgage (CDFI)'::text,'Community Mortgage (CDFI)'::text,'Non-QM'::text,620,80.0,NULL::numeric,3,ARRAY['Primary'],ARRAY['SFR','Condo'],ARRAY['Asset Utilization'],ARRAY['Conventional'],ARRAY['ALL'],100000.0,2500000.0,36,36,NULL::numeric,false,false,false,true,ARRAY[]::text[],'CDFI ATR-exempt. No income docs. No DTI. Primary only. 30yr fixed.','{Conventional}'::text[]),
('Alt Doc Prime','Alt Doc Prime','Non-QM',680,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['Bank Statement','Full Doc','P&L'],ARRAY['ALL'],150000.0,3500000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Premium Non-QM tier.','{"Bank Statement","Full Doc","P&L"}'),
('Alt Doc Advantage','Alt Doc Advantage','Non-QM',640,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],150000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Mid-tier Non-QM.','{"Bank Statement","Full Doc"}'),
('Alt Doc Expanded','Alt Doc Expanded','Non-QM',620,80.0,55.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],150000.0,2500000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'Expanded credit box.','{"Bank Statement","Full Doc"}'),
('Alt Doc Express (DACA eligible)','Alt Doc Express','Non-QM',640,80.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement','Full Doc'],ARRAY['Bank Statement','Full Doc'],ARRAY['ALL'],150000.0,2500000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'DACA borrowers eligible. Streamlined process.','{"Bank Statement","Full Doc"}'),
('DSCR','DSCR','Non-QM',640,85.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0.','{DSCR}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Newfi Wholesale', '3 distinct jumbo AUS products. Real Estate Flipper income program. Asset Utilization. Sequoia up to 90%.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Rainier Bank Statement'::text,'Rainier Bank Statement'::text,'Non-QM'::text,660,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['Bank Statement'],ARRAY['ALL'],150000.0,4000000.0,48,48,NULL::numeric,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt to 90%.','{"Bank Statement"}'::text[]),
('Sequoia Full Doc Non-QM','Sequoia Full Doc Non-QM','Non-QM',620,90.0,55.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,3500000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Full doc Non-QM up to 90%.','{"Full Doc"}'),
('Biscayne Jumbo','Biscayne Jumbo','Agency',680,89.99,43.0,6,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],766550.0,3000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'AUS jumbo - tier 1.','{Jumbo,"Full Doc"}'),
('Lassen Jumbo','Lassen Jumbo','Agency',700,80.0,43.0,12,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],1000000.0,5000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Higher loan amounts jumbo.','{Jumbo,"Full Doc"}'),
('Teton Jumbo','Teton Jumbo','Agency',720,80.0,43.0,12,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc','Asset Utilization'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],1500000.0,5000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Super jumbo tier with asset qualification.','{Jumbo,"Full Doc"}'),
('DSCR','DSCR','Non-QM',680,80.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2500000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0.','{DSCR}'),
('Real Estate Flipper Income','Real Estate Flipper Income','Non-QM',680,80.0,50.0,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,2000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Qualifies via flipper income.','{"Full Doc"}'),
('Asset Utilization','Asset Utilization','Non-QM',700,80.0,NULL,12,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Asset Utilization'],ARRAY['Asset Utilization'],ARRAY['ALL'],150000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Asset depletion qualifier.','{"Asset Utilization"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Quontic Bank', 'CDFI bank. FN DSCR requires no FICO. Asset Utilization no employment needed. Unique borrower populations.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Lite Doc P&L'::text,'Lite Doc P&L'::text,'Non-QM'::text,680,80.0,NULL::numeric,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['P&L'],ARRAY['P&L'],ARRAY['ALL'],100000.0,3000000.0,36,36,NULL::numeric,false,false,false,true,ARRAY[]::text[],'P&L only. CDFI bank.','{"P&L"}'::text[]),
('Asset Utilization','Asset Utilization','Non-QM',700,80.0,NULL,12,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Asset Utilization'],ARRAY['Asset Utilization'],ARRAY['ALL'],100000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'No employment required.','{"Asset Utilization"}'),
('DSCR','DSCR','Non-QM',680,80.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2500000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'DSCR ≥1.0.','{DSCR}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',NULL,70.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],100000.0,2000000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'No FICO required. OFAC.','{"Foreign National",DSCR}'),
('ITIN Lite Doc','ITIN Lite Doc','Non-QM',680,75.0,NULL,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['P&L'],ARRAY['ITIN','P&L'],ARRAY['ALL'],100000.0,1500000.0,36,36,NULL,false,true,false,true,ARRAY[]::text[],'ITIN with Lite Doc.','{ITIN,"P&L"}'),
('ITIN Investor','ITIN Investor','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['ITIN','DSCR'],ARRAY['ALL'],100000.0,1500000.0,36,36,1.0,false,true,false,true,ARRAY[]::text[],'ITIN investor DSCR.','{ITIN,DSCR}'),
('Community Development','Community Development','Non-QM',640,80.0,50.0,6,ARRAY['Primary'],ARRAY['SFR','Condo'],ARRAY['Full Doc','Bank Statement'],ARRAY['Full Doc','Bank Statement'],ARRAY['ALL'],100000.0,1500000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'CDFI low-mod income community lending.','{"Full Doc","Bank Statement"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('Greenbox Loans', 'Elite DSCR to 85% LTV. No FICO FN/ITIN programs. 1-Year 1099 up to 90% LTV. Manual UW advantage.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Bank Statement'::text,'Bank Statement'::text,'Non-QM'::text,640,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['Bank Statement'],ARRAY['ALL'],150000.0,4000000.0,36,36,NULL::numeric,false,false,false,true,ARRAY[]::text[],'12/24mo bank stmt to 90%.','{"Bank Statement"}'::text[]),
('Full Doc Non-QM','Full Doc Non-QM','Non-QM',640,90.0,55.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Full Doc'],ARRAY['ALL'],150000.0,4000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'Full doc Non-QM.','{"Full Doc"}'),
('P&L Only','P&L Only','Non-QM',660,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['P&L'],ARRAY['P&L'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'CPA P&L.','{"P&L"}'),
('1-Year 1099','1-Year 1099','Non-QM',660,90.0,50.0,3,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['1099'],ARRAY['1099'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'1-yr 1099 up to 90% LTV.','{"1099"}'),
('Asset Utilization','Asset Utilization','Non-QM',680,80.0,NULL,12,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Asset Utilization'],ARRAY['Asset Utilization'],ARRAY['ALL'],150000.0,3000000.0,36,36,NULL,false,false,false,true,ARRAY[]::text[],'Asset depletion.','{"Asset Utilization"}'),
('Elite DSCR','Elite DSCR','Non-QM',680,85.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,3000000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'Top tier DSCR to 85%.','{DSCR}'),
('DSCR Standard','DSCR Standard','Non-QM',640,80.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2500000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'Standard DSCR.','{DSCR}'),
('DSCR 5-8 Unit','DSCR 5-8 Unit','Non-QM',680,75.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','5-8 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],250000.0,2500000.0,36,36,1.0,false,false,false,true,ARRAY[]::text[],'5-8 unit.','{DSCR}'),
('Foreign National DSCR','Foreign National DSCR','Non-QM',NULL,70.0,NULL,12,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['Foreign National','DSCR'],ARRAY['ALL'],150000.0,2000000.0,NULL,NULL,1.0,true,false,false,true,ARRAY[]::text[],'No FICO. FN DSCR.','{"Foreign National",DSCR}'),
('ITIN Bank Statement','ITIN Bank Statement','Non-QM',NULL,80.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['ITIN','Bank Statement'],ARRAY['ALL'],100000.0,1500000.0,36,36,NULL,false,true,false,true,ARRAY[]::text[],'No FICO ITIN bank stmt.','{ITIN,"Bank Statement"}'),
('ITIN Full Doc','ITIN Full Doc','Non-QM',NULL,80.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['ITIN','Full Doc'],ARRAY['ALL'],100000.0,1500000.0,36,36,NULL,false,true,false,true,ARRAY[]::text[],'No FICO ITIN full doc.','{ITIN,"Full Doc"}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('NewRez', 'AUS required all products. No manual UW. No ITIN eligible. Jumbo/Non-Agency defers to Product Profiles.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Conventional Conforming'::text,'Conventional Conforming'::text,'Agency'::text,620,97.0,NULL::numeric,NULL::int,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL::numeric,NULL::int,NULL::int,NULL::numeric,false,false,false,true,ARRAY[]::text[],'AUS required. No manual UW.','{Conventional,"Full Doc"}'::text[]),
('FHA','FHA','Agency',580,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'AUS required.','{FHA}'),
('VA','VA','Agency',620,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['VA'],ARRAY['VA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard VA AUS.','{VA}'),
('USDA','USDA','Agency',640,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR'],ARRAY['Full Doc'],ARRAY['USDA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'GUS approval.','{USDA}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);

WITH ins_lender AS (
  INSERT INTO public.lenders (name, niche_advantages, states_licensed) VALUES ('UWM', 'Largest wholesale lender. Elite pricing tiers. State DPA programs (CalHFA, Hometown Heroes). Full product depth.', ARRAY['ALL']::text[]) RETURNING id
)
INSERT INTO public.loan_programs (lender_id, product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags)
SELECT ins_lender.id, x.* FROM ins_lender, (VALUES
('Conventional Conforming'::text,'Conventional Conforming'::text,'Agency'::text,620,97.0,NULL::numeric,NULL::int,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Conventional','Full Doc'],ARRAY['ALL'],75000.0,NULL::numeric,NULL::int,NULL::int,NULL::numeric,false,false,false,true,ARRAY[]::text[],'Standard conforming. Elite pricing.','{Conventional,"Full Doc"}'::text[]),
('FHA','FHA','Agency',580,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['FHA'],ARRAY['FHA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard FHA.','{FHA}'),
('VA','VA','Agency',620,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['VA'],ARRAY['VA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'Standard VA.','{VA}'),
('USDA','USDA','Agency',640,100.0,NULL,NULL,ARRAY['Primary'],ARRAY['SFR'],ARRAY['Full Doc'],ARRAY['USDA'],ARRAY['ALL'],100000.0,NULL,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'GUS approval.','{USDA}'),
('Jumbo','Jumbo','Agency',700,89.99,43.0,6,ARRAY['Primary','Second Home'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Full Doc'],ARRAY['Jumbo','Full Doc'],ARRAY['ALL'],766550.0,5000000.0,NULL,NULL,NULL,false,false,false,true,ARRAY[]::text[],'AUS jumbo to $5M.','{Jumbo,"Full Doc"}'),
('Bank Statement Non-QM','Bank Statement Non-QM','Non-QM',660,85.0,50.0,6,ARRAY['Primary','Second Home','Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['Bank Statement'],ARRAY['Bank Statement'],ARRAY['ALL'],150000.0,3000000.0,48,48,NULL,false,false,false,true,ARRAY[]::text[],'Bank stmt Non-QM.','{"Bank Statement"}'),
('DSCR','DSCR','Non-QM',680,80.0,NULL,6,ARRAY['Investment'],ARRAY['SFR','Condo','2-4 Unit'],ARRAY['DSCR'],ARRAY['DSCR'],ARRAY['ALL'],100000.0,2500000.0,48,48,1.0,false,false,false,true,ARRAY[]::text[],'Standard DSCR.','{DSCR}'),
('State DPA (CalHFA, Hometown Heroes)','State DPA','Agency',640,96.5,NULL,NULL,ARRAY['Primary'],ARRAY['SFR','Condo'],ARRAY['Full Doc','FHA'],ARRAY['Conventional','FHA'],ARRAY['CA'],100000.0,NULL,NULL,NULL,NULL,false,false,true,true,ARRAY[]::text[],'CalHFA + Hometown Heroes DPA.','{Conventional,FHA}')
) AS x(product_name, loan_program, product_type, min_fico, max_ltv, max_dti, reserve_months, occupancies, property_types, income_types, loan_types, states, min_loan_amount, max_loan_amount, bk_seasoning_months, fc_seasoning_months, dscr_min, foreign_national_eligible, itin_eligible, dpa_available, gift_funds_allowed, special_programs, notes, tags);