import type { Lender, LenderProduct } from "./types";

export const seedLenders: Lender[] = [
  { id: "lndr_flagstar", name: "Flagstar Bank", aeName: "Maria Chen", aeEmail: "maria.chen@flagstar.example", aePhone: "555-0101", website: "https://flagstar.com", statesLicensed: ["ALL"] },
  { id: "lndr_angeloak", name: "Angel Oak Mortgage", aeName: "David Kim", aeEmail: "dkim@angeloakms.example", aePhone: "555-0202", website: "https://angeloakms.com", statesLicensed: ["ALL"] },
  { id: "lndr_limaone", name: "Lima One Capital", aeName: "Sarah Brooks", aeEmail: "sbrooks@limaone.example", aePhone: "555-0303", website: "https://limaone.com", statesLicensed: ["ALL"] },
  { id: "lndr_carrington", name: "Carrington Mortgage", aeName: "Tony Reyes", aeEmail: "treyes@carrington.example", aePhone: "555-0404", website: "https://carringtonms.com", statesLicensed: ["ALL"] },
  { id: "lndr_kindlending", name: "Kind Lending", aeName: "Priya Patel", aeEmail: "ppatel@kindlending.example", aePhone: "555-0505", website: "https://kindlending.com", statesLicensed: ["ALL"] },
];

export const seedProducts: LenderProduct[] = [
  // Flagstar
  {
    id: "prd_flagstar_dpa",
    lenderId: "lndr_flagstar",
    productName: "Flagstar DPA Advantage",
    minFico: 580,
    maxLtv: 96.5,
    maxDti: 50,
    incomeTypesAllowed: ["W2", "Self-Employed 1099"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit"],
    loanTypes: ["FHA", "Conventional"],
    dpaAvailable: true,
    dpaMinFico: 580,
    giftFundsAllowed: true,
    occupancies: ["Primary"],
    states: ["ALL"],
    specialPrograms: ["First-Time Buyer", "Gift funds"],
    notes: "Up to 5% DPA on FHA. Must be primary residence. HUD-approved counseling required <620 FICO.",
    tags: ["DPA Programs", "Go-To"],
  },
  {
    id: "prd_flagstar_jumbo",
    lenderId: "lndr_flagstar",
    productName: "Flagstar Jumbo Elite",
    minFico: 720,
    maxLtv: 89.99,
    maxDti: 43,
    incomeTypesAllowed: ["W2", "Self-Employed 1099"],
    propertyTypesAllowed: ["SFR", "Condo"],
    loanTypes: ["Jumbo"],
    dpaAvailable: false,
    giftFundsAllowed: true,
    occupancies: ["Primary", "Second Home"],
    states: ["ALL"],
    specialPrograms: [],
    notes: "Loans up to $3M. 6 months reserves required.",
    tags: ["Go-To"],
  },

  // Angel Oak
  {
    id: "prd_angeloak_bankstmt",
    lenderId: "lndr_angeloak",
    productName: "Angel Oak Bank Statement",
    minFico: 660,
    maxLtv: 90,
    maxDti: 50,
    incomeTypesAllowed: ["Bank Statement", "Self-Employed 1099"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit"],
    loanTypes: ["Non-QM"],
    dpaAvailable: false,
    giftFundsAllowed: true,
    occupancies: ["Primary", "Second Home", "Investment"],
    states: ["ALL"],
    specialPrograms: ["Co-borrower"],
    notes: "12 or 24 month bank statements. Self-employed 2+ years. Personal or business accounts accepted.",
    tags: ["Non-QM Specialty", "Go-To"],
  },
  {
    id: "prd_angeloak_assetqual",
    lenderId: "lndr_angeloak",
    productName: "Angel Oak Asset Qualifier",
    minFico: 700,
    maxLtv: 80,
    maxDti: 50,
    incomeTypesAllowed: ["Retired/Asset Depletion"],
    propertyTypesAllowed: ["SFR", "Condo"],
    loanTypes: ["Non-QM"],
    dpaAvailable: false,
    giftFundsAllowed: false,
    occupancies: ["Primary", "Second Home"],
    states: ["ALL"],
    specialPrograms: [],
    notes: "$500k+ post-close liquid assets required. No income docs needed.",
    tags: ["Non-QM Specialty"],
  },
  {
    id: "prd_angeloak_foreign",
    lenderId: "lndr_angeloak",
    productName: "Angel Oak Foreign National",
    minFico: 0,
    maxLtv: 70,
    maxDti: 50,
    incomeTypesAllowed: ["DSCR/No-Doc", "Bank Statement"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit"],
    loanTypes: ["Non-QM", "DSCR"],
    dpaAvailable: false,
    giftFundsAllowed: false,
    occupancies: ["Investment", "Second Home"],
    states: ["ALL"],
    specialPrograms: ["Foreign National", "ITIN"],
    notes: "No US credit required. ITIN accepted. 12 months reserves.",
    tags: ["Non-QM Specialty"],
  },

  // Lima One
  {
    id: "prd_limaone_dscr",
    lenderId: "lndr_limaone",
    productName: "Lima One DSCR Rental",
    minFico: 660,
    maxLtv: 80,
    maxDti: 99,
    incomeTypesAllowed: ["DSCR/No-Doc"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit", "5+ Unit Multifamily"],
    loanTypes: ["DSCR"],
    dpaAvailable: false,
    giftFundsAllowed: false,
    occupancies: ["Investment"],
    states: ["ALL"],
    specialPrograms: [],
    notes: "DSCR 1.0+ for max LTV. Down to 0.75 DSCR with LTV reduction. No income/employment verification.",
    tags: ["Go-To"],
  },
  {
    id: "prd_limaone_bridge",
    lenderId: "lndr_limaone",
    productName: "Lima One BridgePlus",
    minFico: 680,
    maxLtv: 85,
    maxDti: 99,
    incomeTypesAllowed: ["DSCR/No-Doc"],
    propertyTypesAllowed: ["SFR", "2-4 Unit", "5+ Unit Multifamily", "Mixed Use"],
    loanTypes: ["Bridge", "Hard Money"],
    dpaAvailable: false,
    giftFundsAllowed: false,
    occupancies: ["Investment"],
    states: ["ALL"],
    specialPrograms: [],
    notes: "12-24 month interest-only bridge. Up to 100% rehab. Asset-based.",
    tags: [],
  },

  // Carrington
  {
    id: "prd_carrington_flexfha",
    lenderId: "lndr_carrington",
    productName: "Carrington Flexible Advantage FHA",
    minFico: 550,
    maxLtv: 96.5,
    maxDti: 56.99,
    incomeTypesAllowed: ["W2", "Self-Employed 1099"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit", "Manufactured Home" as never].filter(Boolean) as never,
    loanTypes: ["FHA", "VA", "USDA"],
    dpaAvailable: true,
    dpaMinFico: 600,
    giftFundsAllowed: true,
    occupancies: ["Primary"],
    states: ["ALL"],
    specialPrograms: ["First-Time Buyer", "Gift funds", "Manufactured Home"],
    notes: "550 FICO floor on FHA. Manual underwrite for credit events. Manufactured homes OK.",
    tags: ["DPA Programs", "Go-To"],
  },
  {
    id: "prd_carrington_va",
    lenderId: "lndr_carrington",
    productName: "Carrington VA Champion",
    minFico: 580,
    maxLtv: 100,
    maxDti: 60,
    incomeTypesAllowed: ["W2", "Self-Employed 1099", "Retired/Asset Depletion"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit"],
    loanTypes: ["VA"],
    dpaAvailable: false,
    giftFundsAllowed: true,
    occupancies: ["Primary"],
    states: ["ALL"],
    specialPrograms: ["Gift funds"],
    notes: "100% LTV. VA funding fee can be financed. Residual income matters more than DTI.",
    tags: [],
  },

  // Kind Lending
  {
    id: "prd_kindlending_conv",
    lenderId: "lndr_kindlending",
    productName: "Kind Conventional Plus",
    minFico: 620,
    maxLtv: 97,
    maxDti: 50,
    incomeTypesAllowed: ["W2", "Self-Employed 1099"],
    propertyTypesAllowed: ["SFR", "Condo", "2-4 Unit"],
    loanTypes: ["Conventional"],
    dpaAvailable: true,
    dpaMinFico: 620,
    giftFundsAllowed: true,
    occupancies: ["Primary", "Second Home", "Investment"],
    states: ["ALL"],
    specialPrograms: ["First-Time Buyer", "Gift funds", "Co-borrower"],
    notes: "HomeReady & Home Possible eligible. Non-occupant co-borrower OK.",
    tags: ["Go-To"],
  },
  {
    id: "prd_kindlending_itin",
    lenderId: "lndr_kindlending",
    productName: "Kind ITIN Pathway",
    minFico: 640,
    maxLtv: 80,
    maxDti: 50,
    incomeTypesAllowed: ["W2", "Self-Employed 1099", "Bank Statement"],
    propertyTypesAllowed: ["SFR", "Condo"],
    loanTypes: ["Non-QM"],
    dpaAvailable: false,
    giftFundsAllowed: true,
    occupancies: ["Primary"],
    states: ["ALL"],
    specialPrograms: ["ITIN", "Gift funds"],
    notes: "ITIN borrowers welcome. 2 years credit history required (alt-tradelines OK).",
    tags: ["Non-QM Specialty"],
  },
];
